name: Test

on: [pull_request]

jobs:
  build:
    name: build (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.12']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade requests
    - name: Verify JSON
      run: python scripts/json_verify.py
    - name: Diff current blocklist with remote
      run: python scripts/compare_remote.py
    - name: Diff current blocklist with Disconnect
      run: python scripts/compare_remote.py -d
